sudo: false
language: go

go:
  - 1.6.x
  - 1.7.x
  - 1.8.x

notifications:
  email: false

script:
  - go get github.com/kardianos/govendor
  - govendor sync
  - go test -v ./pmm
  - go build -o bin/pmm-admin
