sudo: false
language: go

go:
  - 1.6.*
  - 1.7.*
  - 1.8.*

notifications:
  email: false

script:
  - go get github.com/kardianos/govendor
  - govendor sync
  - go test -v ./pmm
  - go build -o bin/pmm-admin
