sudo: false
language: go

go:
  - 1.7.x
  - 1.8.x

services:
  - mysql
  - mongodb

notifications:
  email: false

script:
  - go get -u github.com/Masterminds/glide
  - glide install
  - pkgs=$(go list ./... | grep -v /vendor/)
  - go test -v $pkgs
  - go build -o bin/pmm-admin
